# Generated by Django 5.0.6 on 2024-06-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=20, verbose_name='имя')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=20, verbose_name='имя')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('preview', models.ImageField(null=True, upload_to='product/', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('made', models.DateField(auto_now_add=True, verbose_name='изготовлено')),
                ('change', models.DateField(auto_now=True, verbose_name='изменено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
